config/routes.rb
Rails.application.routes.draw do

  root :to => 'users#index'

  resources :users, :only => [:edit, :index, :new, :show, :destroy, :create, :update] do
    resources :skills, :only => [:edit, :index, :new, :show, :destroy, :create, :update]
    resources :projects, :only => [:edit, :index, :new, :show, :destroy, :create, :update]
  end

  resources :skills, :only => [:edit, :index, :new, :show, :destroy, :create, :update] do
    resources :projects, :only => [:edit, :index, :new, :show, :destroy, :create, :update]
  end

  resources :projects, :only => [:edit, :index, :new, :show, :destroy, :create, :update] do
    resources :skills, :only => [:edit, :index, :new, :show, :destroy, :create, :update]
  end

end

app/models/concerns/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true
  validates :short_description, :presence => true
  validates :long_description, :presence => true
  validates :category, :presence => true
  validates :coworkers, :presence => true
  validates :code_url, :presence => true
  validates :hosted_url, :presence => true
  validates :project_date, :presence => true
  validates :skill_id, :presence => true
  validates :user_id, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true
  validates :short_description, :presence => true
  validates :long_description, :presence => true
  validates :category, :presence => true
  validates :coworkers, :presence => true
  validates :code_url, :presence => true
  validates :hosted_url, :presence => true
  validates :project_date, :presence => true
  belongs_to :user
  has_and_belongs_to_many :skills
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :category, :presence => true
  belongs_to :user
  has_and_belongs_to_many :projects
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true
  validates :short_description, :presence => true
  validates :long_description, :presence => true
  validates :title, :presence => true
  validates :app_role, :presence => true
  validates :phone, :presence => true
  validates :email, :presence => true
  validates :code_url, :presence => true
  validates :hosted_url, :presence => true
  has_many :skills
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @project = @user.projects.new
  end

  def create
    @user = User.find(params[:user_id])
    @project = @user.projects.new(project_params)
    if @project.save
      flash[:notice] = "Project added."
      redirect_to user_path(@project.user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
  end

  def update
    @user= User.find(params[:user_id])
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project updated."
      redirect_to user_path(@project.user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to user_path(@project.user)
  end

private
  def project_params
    params.require(:project).permit(:name, :short_description, :long_description, :category, :coworkers, :code_url, :hosted_url, :project_date)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    @projects = Project.all
    @skill = Skill.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @skill = @user.skills.new
  end

  def create
    @user = User.find(params[:user_id])
    @skill = @user.skills.new(skill_params)
    if @skill.save
      flash[:notice] = "Skill added."
      redirect_to user_path(@skill.user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @skill = Skill.find(params[:id])
  end

  def update
    @user= User.find(params[:user_id])
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      flash[:notice] = "Skill updated."
      redirect_to user_path(@skill.user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to user_path(@skill.user)
  end

private
  def skill_params
    params.require(:skill).permit(:name, :description, :category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User added."
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user= User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User updated."
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :short_description, :long_description, :title ,:app_role, :phone, :email, :code_url, :hosted_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= flash[:alert] %>
  <%= flash[:notice] %>

  <%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= render('layouts/errors', :object => @project) %>

<%= form_for [@user, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :short_description %>
  <%= f.text_field :short_description %>

  <%= f.label :long_description %>
  <%= f.text_field :long_description %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :coworkers %>
  <%= f.text_field :coworkers %>

  <%= f.label :code_url %>
  <%= f.text_field :code_url %>

  <%= f.label :hosted_url %>
  <%= f.text_field :hosted_url %>

  <%= f.label :project_date %>
  <%= f.text_field :project_date %>

  <p><%= f.submit %></p>
<% end %>

app/views/projects/edit.html.erb
<% content_for(:title, "Edit Project | Coder Portfolios") %>

<h1>Edit projects</h1>


<%= render "form" %>

app/views/projects/new.html.erb
<% content_for(:title, "New Project | Coder Portfolios") %>

<h1>New project for <%= @user.name %></h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<% content_for(:title, "Show Project | Coder Portfolios") %>

<h1>Name: <%= @project.name %></h1>
<h4>Description: <%= @project.short_description %></h4>
<h4>More: <%= @project.long_description %></h4>
<h4>Category: <%= @project.category %></h4>
<h4>Coworkers: <%= @project.coworkers %></h4>
<h4>Code url: <%= @project.code_url %></h4>
<h4>Hosted url: <%= @project.hosted_url %></h4>
<h4>Project date: <%= @project.project_date %></h4>

<% if @project.skills.any? %>
  <h4>Here are the skills for this project:</h4>

  <ul>
    <% @project.skills.each do |skill| %>
      <li>
        <%= skill.name %> | <%= skill.description %> |
        <%= link_to "Show", user_skill_path(@project, skill) %> |
        <%= link_to "Edit", edit_user_skill_path(@project, skill) %> |
        <%= link_to "Delete", user_skill_path(@project, skill),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>This project has no skills yet!</p>
<% end %>

<%= link_to "Edit", edit_user_project_path(@user, @project) %> |
<%= link_to "Delete", user_project_path(@user, @project),
                         :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %>
<%= link_to "Return to user", user_path(@user) %>

app/views/skills/_form.html.erb
<%= render('layouts/errors', :object => @skill) %>

<%= form_for [@user, @skill] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <p><%= f.submit %></p>
<% end %>

app/views/skills/edit.html.erb
<% content_for(:title, "Edit Skill | Coder Portfolios") %>

<h1>Edit skills</h1>


<%= render "form" %>

app/views/skills/new.html.erb
<% content_for(:title, "New Skill | Coder Portfolios") %>

<h1>New skill for <%= @user.name %></h1>

<%= render 'form' %>

app/views/skills/show.html.erb
<% content_for(:title, "Show Skill | Coder Portfolios") %>

<h1>Name: <%= @skill.name %></h1>
<h4>Description: <%= @skill.description %></h4>
<h4>Category: <%= @skill.category %></h4>

<% if @skill.projects.any? %>
  <h4>Here are the projects for this skill:</h4>

  <ul>
    <% @skill.projects.each do |project| %>
      <li>
        <%= project.name %> | <%= project.short_description %> |
        <%= link_to "Show", user_project_path(@user, project) %> |
        <%= link_to "Edit", edit_user_project_path(@user, project) %> |
        <%= link_to "Delete", user_project_path(@user, project),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>This skill has no projects yet!</p>
<% end %>

<p>Add a project:</p>



<%= link_to "Edit", edit_user_skill_path(@user, @skill) %> |
<%= link_to "Delete", user_skill_path(@user, @skill),
                         :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %>
<%= link_to "Return to user", user_path(@user) %>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :short_description %>
<%= f.text_field :short_description %>

<%= f.label :long_description %>
<%= f.text_field :long_description %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :app_role %>
<%= f.text_field :app_role %>

<%= f.label :phone %>
<%= f.text_field :phone %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :code_url %>
<%= f.text_field :code_url %>

<%= f.label :hosted_url %>
<%= f.text_field :hosted_url %>

<%= f.submit  %>

<% end %>

app/views/users/edit.html.erb
<% content_for(:title, "Edit User | Coder Portfolios") %>

<h1>Edit user</h1>


<%= render "form" %>

app/views/users/index.html.erb
<% content_for(:title, "Coder Portfolios") %>

<h1>Coder Portfolios</h1>

<h4>Show or Edit a Coder</h4>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %>:
    <%= link_to "Edit", edit_user_path(user) %>  <%= link_to "Delete", user_path(user),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %>
    </li>
  <% end %>

</ul>
<p><%= link_to "Add a new coder", new_user_path %></p>

app/views/users/new.html.erb
<% content_for(:title, "Create User | Coder Portfolios") %>

<h1>New user</h1>


<p>
<%= render "form" %>
</p>

app/views/users/show.html.erb
<% content_for(:title, "Show User | Coder Portfolios") %>

<h1>Name: <%= @user.name %></h1>
<h4>Title: <%= @user.title %></h4>
<h4>Description: <%= @user.short_description %></h4>
<h4>More: <%= @user.long_description %></h4>
<h4>User type: <%= @user.app_role %></h4>
<h4>Phone: <%= @user.phone %></h4>
<h4>Email: <%= @user.email %></h4>
<h4>Code Repo: <%= @user.code_url %></h4>
<h4>Hosted App URL: <%= @user.hosted_url %></h4>

<% if @user.skills.any? %>
  <h4>Here are the skills for this user:</h4>

  <ul>
    <% @user.skills.each do |skill| %>
      <li>
        <%= skill.name %> | <%= skill.description %> |
        <%= link_to "Show", user_skill_path(@user, skill) %> |
        <%= link_to "Edit", edit_user_skill_path(@user, skill) %> |
        <%= link_to "Delete", user_skill_path(@user, skill),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>This user has no skills yet!</p>
<% end %>

<% if @user.projects.any? %>
  <h4>Here are the projects for this user:</h4>

  <ul>
    <% @user.projects.each do |project| %>
      <li>
        <%= project.name %> | <%= project.short_description %> |
        <%= link_to "Show", user_project_path(@user, project) %> |
        <%= link_to "Edit", edit_user_project_path(@user, project) %> |
        <%= link_to "Delete", user_project_path(@user, project),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>This user has no projects yet!</p>
<% end %>

<p><%= link_to "Add a skill", new_user_skill_path(@user) %></p>
<p><%= link_to "Add a project", new_user_project_path(@user) %></p>

<p><%= link_to "Edit", edit_user_path(@user) %></p>
<p><%= link_to "Delete", user_path(@user),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to users", users_path %></p>